#  Copyright (c) 2025 Tom Villani, Ph.D.
#
# src/all2md/parsers/rtf2markdown.py

"""Rich Text Format (RTF) to Markdown conversion module.

This module provides functionality to convert Rich Text Format (RTF) documents
to Markdown, preserving essential formatting and structure. It uses the pyth
library for parsing RTF documents.

Key Features
------------
- Text formatting preservation (bold, italic, underline)
- Basic list detection (bulleted and numbered)
- Image extraction and handling via unified attachment processing
- Paragraph and line break management
- Smart quote conversion

Limitations
-----------
- **Tables**: RTF tables are not detected as structured tables and will appear
  as regular paragraphs. The pyth library does not provide table parsing.
- **Complex RTF files**: Files generated by Microsoft Word with extensive
  formatting may fail to parse due to pyth library limitations with modern RTF.
- **Hyperlinks**: Links are not preserved in the conversion.
- **Headers**: RTF heading styles are not detected; all text appears as paragraphs.
- **Advanced formatting**: Features like text colors, fonts, and advanced
  layouts are not preserved.

Dependencies
------------
- pyth: For parsing the RTF document structure

Note
----
For best results, use RTF files with simpler formatting. Complex RTF files
generated by modern word processors may encounter parsing errors.
"""
from __future__ import annotations

import io
import logging
import re
from pathlib import Path
from typing import IO, TYPE_CHECKING, Any, Optional, Union

from all2md.converter_metadata import ConverterMetadata
from all2md.exceptions import MarkdownConversionError
from all2md.options import MarkdownOptions, RtfOptions
from all2md.utils.attachments import create_attachment_sequencer, process_attachment
from all2md.utils.inputs import format_special_text, validate_and_convert_input
from all2md.utils.metadata import DocumentMetadata, prepend_metadata_if_enabled

# Type checking imports for static analysis without runtime overhead
if TYPE_CHECKING:
    from pyth.document import Document, Image, List, ListEntry, Paragraph, Text

logger = logging.getLogger(__name__)


def extract_rtf_metadata(doc: Document) -> DocumentMetadata:
    """Extract metadata from RTF document.

    Parameters
    ----------
    doc : Document
        Parsed RTF document from pyth

    Returns
    -------
    DocumentMetadata
        Extracted metadata
    """
    # Import pyth types for isinstance checks
    from pyth.document import Image, List, ListEntry, Paragraph, Text

    metadata = DocumentMetadata()

    # RTF documents parsed by pyth have limited metadata access
    # Most RTF metadata is not easily accessible through the pyth library
    # We can extract some basic document statistics and content analysis

    if not doc or not doc.content:
        return metadata

    # Count different element types
    paragraph_count = 0
    list_count = 0
    image_count = 0
    text_content = []

    def analyze_element(element: Any) -> None:
        nonlocal paragraph_count, list_count, image_count

        if isinstance(element, Paragraph):
            paragraph_count += 1
            # Extract text content for analysis
            for item in element.content or []:
                if isinstance(item, Text):
                    if isinstance(item.content, list):
                        text_content.extend(item.content)
                    else:
                        text_content.append(str(item.content))
                elif isinstance(item, Image):
                    image_count += 1
        elif isinstance(element, List):
            list_count += 1
            # Recursively analyze list content
            for entry in element.content or []:
                analyze_element(entry)
        elif isinstance(element, ListEntry):
            # Analyze list entry content
            for item in element.content or []:
                analyze_element(item)

    # Analyze all document content
    for element in doc.content:
        analyze_element(element)

    # Set document statistics
    if paragraph_count > 0:
        metadata.custom['paragraph_count'] = paragraph_count

    if list_count > 0:
        metadata.custom['list_count'] = list_count

    if image_count > 0:
        metadata.custom['image_count'] = image_count

    # Analyze text content
    if text_content:
        full_text = ' '.join(str(t) for t in text_content if t)

        # Word count
        words = full_text.split()
        if words:
            metadata.custom['word_count'] = len(words)

        # Character count
        if full_text.strip():
            metadata.custom['character_count'] = len(full_text.strip())

        # Try to extract title from first significant text
        # Look for title-like content (short first line or heading)
        text_lines = [line.strip() for line in full_text.split('\n') if line.strip()]
        if text_lines:
            first_line = text_lines[0]
            # If the first line is reasonably short and looks like a title
            if len(first_line) < 100 and not first_line.endswith('.'):
                # Check if it's likely a title (short, no sentence ending)
                words_in_first = first_line.split()
                if 1 <= len(words_in_first) <= 15:  # Reasonable title length
                    metadata.title = first_line

    # RTF document type
    metadata.custom['document_type'] = 'rtf'
    metadata.custom['format'] = 'Rich Text Format'

    return metadata


def rtf_to_markdown(
        input_data: Union[str, Path, IO[bytes]], options: Optional[RtfOptions] = None
) -> str:
    """Convert an RTF document to Markdown format.

    Processes RTF documents from various input sources and converts them to
    well-formatted Markdown, preserving structure and formatting like tables,
    lists, and text styles.

    Parameters
    ----------
    input_data : str, pathlib.Path, or file-like object
        RTF content to convert. Can be:
        - String path to an RTF file
        - pathlib.Path object pointing to an RTF file
        - File-like object (e.g., BytesIO) containing RTF data
    options : RtfOptions or None, default None
        Configuration options for RTF conversion. If None, uses default settings.

    Returns
    -------
    str
        Markdown representation of the RTF document.

    Raises
    ------
    InputError
        If input type is not supported or file cannot be read.
    MarkdownConversionError
        If the `pyth` library is not installed or if RTF parsing fails.
    """
    # Lazy import of heavy pyth dependencies
    try:
        from pyth.plugins.rtf15.reader import Rtf15Reader
    except ImportError:
        Rtf15Reader = None

    if Rtf15Reader is None:
        raise MarkdownConversionError(
            "`pyth` library is required for RTF conversion. Install with: pip install pyth",
            conversion_stage="dependency_check",
        )

    if options is None:
        options = RtfOptions()

    try:
        doc_input, _ = validate_and_convert_input(
            input_data, supported_types=["path-like", "file-like"]
        )

        if isinstance(doc_input, (str, Path)):
            with open(doc_input, "rb") as f:
                doc = Rtf15Reader.read(f)
            base_filename = Path(doc_input).stem
        elif hasattr(doc_input, "read"):
            # Ensure we have a binary stream
            if isinstance(doc_input, io.TextIOBase):
                raise MarkdownConversionError("RTF input stream must be binary, not text.")
            doc = Rtf15Reader.read(doc_input)
            # Try to get filename from file object's name attribute
            if hasattr(doc_input, 'name') and doc_input.name not in (None, 'unknown'):
                base_filename = Path(doc_input.name).stem
            else:
                base_filename = "document"
        else:
            raise MarkdownConversionError(f"Unsupported input type for RTF conversion: {type(doc_input)}")

    except Exception as e:
        if isinstance(e, MarkdownConversionError):
            raise
        raise MarkdownConversionError(
            f"Failed to read or parse RTF document: {e}",
            conversion_stage="document_parsing",
            original_error=e,
        ) from e

    # Extract metadata if requested
    metadata = None
    if options.extract_metadata:
        metadata = extract_rtf_metadata(doc)

    # Extract base filename for standardized attachment naming
    if 'base_filename' not in locals():
        base_filename = "document"

    # Create attachment sequencer for consistent filename generation
    attachment_sequencer = create_attachment_sequencer()

    # Use AST-based conversion path
    from all2md.parsers.rtf import RtfToAstConverter
    from all2md.ast import MarkdownRenderer

    # Convert to AST
    ast_converter = RtfToAstConverter(
        options=options,
        base_filename=base_filename,
        attachment_sequencer=attachment_sequencer,
    )
    ast_document = ast_converter.convert_to_ast(doc)

    # Render AST to markdown
    md_opts = options.markdown_options if options.markdown_options else MarkdownOptions()
    renderer = MarkdownRenderer(md_opts)
    markdown_content = renderer.render(ast_document)

    # Prepend metadata if enabled
    result = prepend_metadata_if_enabled(markdown_content.strip(), metadata, options.extract_metadata)

    return result


# Converter metadata for registration
CONVERTER_METADATA = ConverterMetadata(
    format_name="rtf",
    extensions=[".rtf"],
    mime_types=["application/rtf", "text/rtf"],
    magic_bytes=[
        (b"{\\rtf", 0),
    ],
    converter_module="all2md.parsers.rtf2markdown",
    converter_function="rtf_to_markdown",
    required_packages=[("pyth3", "pyth", "")],
    import_error_message="RTF conversion requires 'pyth3'. Install with: pip install pyth3",
    options_class="RtfOptions",
    description="Convert Rich Text Format documents to Markdown",
    priority=4
)
