#  Copyright (c) 2025 Tom Villani, Ph.D.
"""Unit tests for the man(7) page parser."""

from __future__ import annotations

import logging

import pytest

from all2md import from_ast, to_markdown
from all2md.ast import (
    BlockQuote,
    Code,
    CodeBlock,
    DefinitionList,
    Document,
    Emphasis,
    Heading,
    LineBreak,
    Link,
    List,
    Node,
    Paragraph,
    Strong,
    Table,
    Text,
)
from all2md.converter_registry import registry
from all2md.options.man import ManParserOptions
from all2md.parsers.man import ManParser, _is_man_content

pytestmark = pytest.mark.unit

# The standard preamble Pod::Man writes at the top of every Perl manual page,
# followed by a short page that uses its macros and strings.
POD2MAN_PAGE = r""".\" -*- mode: troff; coding: utf-8 -*-
.\" Automatically generated by Pod::Man 5.01 (Pod::Simple 3.43)
.\"
.\" Standard preamble:
.\" ========================================================================
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.\" \*(C` and \*(C' are quotes in nroff, nothing in troff, for use with C<>.
.ie n \{\
.    ds C` ""
.    ds C' ""
'br\}
.el\{\
.    ds C`
.    ds C'
'br\}
.\"
.\" Escape single quotes in literal strings from groff's Unicode transform.
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\"
.\" Avoid warning from groff about undefined register 'F'.
.de IX
..
.nr rF 0
.if \n(.g .if rF .nr rF 1
.if (\n(rF:(\n(.g==0)) \{\
.    if \nF \{\
.        de IX
.        tm Index:\\$1\t\\n%\t"\\$2"
..
.        if !\nF==2 \{\
.            nr % 0
.            nr F 2
.        \}
.    \}
.\}
.rr rF
.\" ========================================================================
.\"
.IX Title "FOO 1"
.TH FOO 1 2024-01-01 "perl v5.38.0" "User Contributed Perl Documentation"
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH NAME
foo \- frobnicate the widgets
.SH SYNOPSIS
.IX Header "SYNOPSIS"
.Vb 2
\&    use Foo;
\&    my $x = Foo\->new;
.Ve
.SH DESCRIPTION
.IX Header "DESCRIPTION"
Call \f(CW\*(C`frob\*(C'\fR to \fBfrobnicate\fR, it\*(Aqs easy.
.IP \fB\-\-verbose\fR 4
.IX Item "--verbose"
Be loud.
.SH OPTIONS
.IP \(bu 4
first
.IP \(bu 4
second
"""


def parse(source: str, **options: object) -> Document:
    return ManParser(ManParserOptions(**options) if options else None).parse(source)  # type: ignore[arg-type]


def markdown(source: str, **options: object) -> str:
    return from_ast(parse(source, **options), "markdown").strip()


def blocks(doc: Document, kind: type) -> list:
    return [node for node in doc.children if isinstance(node, kind)]


def inline_shape(nodes: list[Node]) -> str:
    """Render inline nodes compactly: B[...] strong, I[...] emphasis, C[...] code, BR break."""
    out = []
    for node in nodes:
        if isinstance(node, Strong):
            out.append(f"B[{inline_shape(node.content)}]")
        elif isinstance(node, Emphasis):
            out.append(f"I[{inline_shape(node.content)}]")
        elif isinstance(node, Code):
            out.append(f"C[{node.content}]")
        elif isinstance(node, Link):
            out.append(f"L<{node.url}>[{inline_shape(node.content)}]")
        elif isinstance(node, LineBreak):
            out.append("BR")
        elif isinstance(node, Text):
            out.append(node.content)
        else:
            out.append(type(node).__name__)
    return "".join(out)


def first_paragraph(doc: Document) -> str:
    return inline_shape(blocks(doc, Paragraph)[0].content)


class TestDetection:
    """The content detector, and routing through the registry."""

    @pytest.mark.parametrize(
        "source",
        [
            b".TH LS 1\n.SH NAME\n",
            b'.\\" Copyright notice\n.\\"\n\n.TH LS 1 2024-01-01\n',
            b'\'\\" t\n.\\" tbl hint first\n.TH ASCII 7\n',
            b'.\\" only a long license header\n' * 60,
            POD2MAN_PAGE.encode()[:1024],
            POD2MAN_PAGE.encode(),
        ],
        ids=["th-first", "after-comments", "tbl-hint", "comments-only", "pod2man-first-kb", "pod2man-whole"],
    )
    def test_detects_man_pages(self, source: bytes) -> None:
        assert _is_man_content(source)

    @pytest.mark.parametrize(
        "source",
        [
            b"",
            b"2024-01-01 12:00:00 INFO server started\n",
            b"Some text\n.TH LATER 1\n",
            b'.\\" mdoc\n.Dd January 1, 2024\n.Dt LS 1\n',
            b".so man7/groff_man.7\n",
            b".TH X 1\x00binary",
        ],
        ids=["empty", "log", "text-before-th", "mdoc", "so-stub", "binary"],
    )
    def test_rejects_other_content(self, source: bytes) -> None:
        assert not _is_man_content(source)

    def test_extension_and_content_route_to_man(self, tmp_path) -> None:
        page = tmp_path / "ls.1"
        page.write_bytes(b".TH LS 1\n.SH NAME\nls \\- list\n")
        assert registry.detect_format(str(page)) == "man"

    def test_rotated_log_with_man_extension_stays_plaintext(self, tmp_path) -> None:
        log = tmp_path / "app.log.1"
        log.write_bytes(b"2024-01-01 12:00:00 INFO server started\n")
        assert registry.detect_format(str(log)) == "plaintext"

    def test_content_alone_routes_to_man(self) -> None:
        assert registry.detect_format(b'.\\" header\n.TH LS 1\n.SH NAME\nls \\- list\n') == "man"

    def test_unknown_extension_routes_by_content(self, tmp_path) -> None:
        page = tmp_path / "Foo.3pm"
        page.write_bytes(POD2MAN_PAGE.encode())
        assert registry.detect_format(str(page)) == "man"


class TestTitleAndHeadings:
    """.TH metadata, section headings and their options."""

    def test_name_description_keeps_formatted_words(self) -> None:
        doc = parse(".TH FOO 1\n.SH NAME\n\\fBfoo\\fR \\- list \\fBall\\fR \\fIthe\\fR files\n")
        assert doc.metadata["description"] == "list all the files"

    def test_th_fills_metadata_and_title_heading(self) -> None:
        doc = parse(
            '.TH LS 1 2024-03-01 "GNU coreutils 9.4" "User Commands"\n.SH NAME\nls \\- list directory contents\n'
        )
        assert doc.metadata["title"] == "LS(1)"
        assert doc.metadata["description"] == "list directory contents"
        assert doc.metadata["section"] == "1"
        assert doc.metadata["source"] == "GNU coreutils 9.4"
        assert doc.metadata["manual"] == "User Commands"
        headings = blocks(doc, Heading)
        assert [(h.level, inline_shape(h.content)) for h in headings] == [(1, "LS(1)"), (2, "NAME")]

    def test_sections_and_subsections(self) -> None:
        doc = parse(".TH X 1\n.SH DESCRIPTION\ntext\n.SS Details\nmore\n")
        assert [(h.level, inline_shape(h.content)) for h in blocks(doc, Heading)] == [
            (1, "X(1)"),
            (2, "DESCRIPTION"),
            (3, "Details"),
        ]

    def test_without_title_heading(self) -> None:
        doc = parse(".TH X 1\n.SH DESCRIPTION\n.SS Details\n", title_heading=False)
        assert [(h.level, inline_shape(h.content)) for h in blocks(doc, Heading)] == [
            (1, "DESCRIPTION"),
            (2, "Details"),
        ]
        assert doc.metadata["title"] == "X(1)"

    def test_normalize_heading_case(self) -> None:
        doc = parse(".TH X 1\n.SH SEE ALSO\n.SH Mixed Case\n", normalize_heading_case=True)
        assert [inline_shape(h.content) for h in blocks(doc, Heading)][1:] == ["See Also", "Mixed Case"]

    def test_heading_text_on_next_line(self) -> None:
        doc = parse(".TH X 1\n.SH\nEXIT STATUS\n")
        assert inline_shape(blocks(doc, Heading)[-1].content) == "EXIT STATUS"


class TestInline:
    """Fonts, escapes and strings."""

    def test_font_escapes(self) -> None:
        assert first_paragraph(parse("Use \\fBbold\\fR and \\fIitalic\\fP and \\f(CWcode\\fR.\n")) == (
            "Use B[bold] and I[italic] and C[code]."
        )

    def test_previous_font(self) -> None:
        # Spaces at the edge of a font run move outside the formatting.
        assert first_paragraph(parse("\\fBbold \\fIitalic\\fP back\\fR plain\n")) == "B[bold] I[italic] B[back] plain"

    def test_bold_italic_nests_inside_bold(self) -> None:
        source = "\\fBbold with \\f(BIitalic\\fB inside\\fR plain\n"
        assert first_paragraph(parse(source)) == "B[bold with I[italic] inside] plain"

    def test_bold_italic_nests_inside_italic(self) -> None:
        source = "\\fIitalic with \\f(BIbold\\fI inside\\fR\n"
        assert first_paragraph(parse(source)) == "I[italic with B[bold] inside]"

    def test_bold_italic_alone_puts_italic_outside(self) -> None:
        # The CommonMark nesting of ***x***.
        assert first_paragraph(parse("\\f(BIboth\\fR\n")) == "I[B[both]]"

    def test_constant_width_inside_bold(self) -> None:
        source = "\\fBbold \\f(CBcode\\fB bold\\fR and \\fIit \\f(CIc\\fR\n"
        assert first_paragraph(parse(source)) == "B[bold C[code] bold] and I[it C[c]]"

    def test_separate_bold_runs_stay_separate(self) -> None:
        assert first_paragraph(parse("\\fBa\\fR \\fBb\\fR\n")) == "B[a] B[b]"

    def test_font_macros(self) -> None:
        doc = parse(".B bold words\n.I italic\n.BR ls (1),\n.IR file .txt\n")
        assert first_paragraph(doc) == "B[bold words] I[italic] B[ls](1), I[file].txt"

    def test_font_macro_without_arguments_applies_to_next_line(self) -> None:
        assert first_paragraph(parse(".B\nnext line\nplain\n")) == "B[next line] plain"

    def test_font_spans_lines(self) -> None:
        assert first_paragraph(parse("\\fBone\ntwo\\fR three\n")) == "B[one two] three"

    def test_escapes(self) -> None:
        source = "a\\-b \\(em \\[bu] \\e \\&.dot \\(lqq\\(rq \\*(lqs\\*(rq it\\(aqs \\[u00E9] x\\ y\n"
        assert first_paragraph(parse(source)) == (
            "a-b \u2014 \u2022 \\ .dot \u201cq\u201d \u201cs\u201d it's \u00e9 x y"
        )

    def test_size_and_motion_escapes_vanish(self) -> None:
        assert first_paragraph(parse("\\s-1SMALL\\s0 \\h'2n'x\\v'-1'y\\w'abc'z\n")) == "SMALL xyz"

    def test_user_strings(self) -> None:
        assert first_paragraph(parse('.ds Nm frob\n.ds Q "quoted\nRun \\*(Nm, \\*Q.\n')) == "Run frob, quoted."

    def test_comments(self) -> None:
        assert first_paragraph(parse('text \\" a comment\n.\\" whole line\nmore\n')) == "text more"

    def test_continuation_escape_joins_lines(self) -> None:
        assert first_paragraph(parse("\\fBfoo\\fR\\c\nbar\n")) == "B[foo]bar"

    def test_line_break(self) -> None:
        assert first_paragraph(parse("one\n.br\ntwo\n")) == "oneBRtwo"

    def test_indented_line_breaks_once(self) -> None:
        assert first_paragraph(parse("one\n.br\n    two\n   three\n")) == "oneBRtwoBRthree"

    def test_links(self) -> None:
        doc = parse(".UR https://example.com\nthe site\n.UE .\n.MT a@example.com\n.ME\n")
        assert first_paragraph(doc) == ("L<https://example.com>[the site]. L<mailto:a@example.com>[a@example.com]")

    def test_synopsis_macros(self) -> None:
        assert first_paragraph(parse(".SY ls\n.OP \\-l\n.OP \\-w cols\n.YS\n")) == "B[ls] [B[-l]] [B[-w] I[cols]]"

    def test_manual_reference_macro(self) -> None:
        assert first_paragraph(parse("See\n.MR ls 1 .\n")) == "See I[ls](1)."


class TestBlocks:
    """Paragraphs, lists, nesting, code and tables."""

    def test_paragraphs(self) -> None:
        doc = parse("one\ntwo\n.PP\nthree\n\nfour\n")
        assert [inline_shape(p.content) for p in blocks(doc, Paragraph)] == ["one two", "three", "four"]

    def test_tagged_paragraphs_become_definition_list(self) -> None:
        doc = parse(".TP\n.B \\-a\nall entries\n.TP\n\\fB\\-l\\fR\nlong format\n.PP\nafter\n")
        (dl,) = blocks(doc, DefinitionList)
        assert [inline_shape(term.content) for term, _ in dl.items] == ["B[-a]", "B[-l]"]
        assert [inline_shape(desc[0].content[0].content) for _, desc in dl.items] == ["all entries", "long format"]
        assert inline_shape(blocks(doc, Paragraph)[-1].content) == "after"

    def test_tq_joins_terms(self) -> None:
        (dl,) = blocks(parse(".TP\n.B \\-v\n.TQ\n.B \\-\\-verbose\nbe loud\n"), DefinitionList)
        assert [inline_shape(term.content) for term, _ in dl.items] == ["B[-v], B[--verbose]"]

    def test_untagged_ip_continues_the_description(self) -> None:
        (dl,) = blocks(parse(".TP\n.B \\-a\nfirst\n.IP\nsecond\n"), DefinitionList)
        _term, (description,) = dl.items[0]
        assert [inline_shape(p.content) for p in description.content] == ["first", "second"]

    def test_bullets_and_numbers_become_lists(self) -> None:
        doc = parse(".IP \\(bu 2\none\n.IP \\(bu 2\ntwo\n.PP\n.IP 3. 4\nthree\n.IP 4. 4\nfour\n")
        bullets, numbers = blocks(doc, List)
        assert not bullets.ordered and len(bullets.items) == 2
        assert numbers.ordered and numbers.start == 3 and len(numbers.items) == 2

    def test_task_markers_become_task_status(self) -> None:
        source = ".IP \\(bu 2\n[ ] open\n.IP \\(bu 2\n[x] \\fBdone\\fR\n.IP \\(bu 2\n[X]\n.IP \\(bu 2\nplain\n"
        (items,) = blocks(parse(source), List)
        assert [item.task_status for item in items.items] == ["unchecked", "checked", "checked", None]
        assert inline_shape(items.items[0].children[0].content) == "open"
        assert inline_shape(items.items[1].children[0].content) == "B[done]"
        assert items.items[2].children == []

    @pytest.mark.parametrize("text", ["[x]no-space", "[link] text", "[ y ] wide"])
    def test_bracketed_text_is_not_a_task(self, text: str) -> None:
        (items,) = blocks(parse(f".IP \\(bu 2\n{text}\n"), List)
        assert items.items[0].task_status is None
        assert inline_shape(items.items[0].children[0].content) == text

    @pytest.mark.parametrize(
        ("source", "tight"),
        [
            (".IP \\(bu 2\none\n.IP \\(bu 2\ntwo\n", True),
            (".IP \\(bu 2\none\n.RS\n.IP \\(bu 2\ninner\n.RE\n.IP \\(bu 2\ntwo\n", True),
            (".IP \\(bu 2\none\n.IP\nmore\n.IP \\(bu 2\ntwo\n", False),
            (".IP \\(bu 2\none\n.RS\n.EX\ncode\n.EE\n.RE\n.IP \\(bu 2\ntwo\n", False),
        ],
        ids=["single-paragraphs", "nested-list", "second-paragraph", "code-block"],
    )
    def test_list_tightness(self, source: str, tight: bool) -> None:
        # Only a second non-list block loosens a list: Markdown's "- a" + "  - b" is tight.
        (top,) = blocks(parse(source), List)
        assert top.tight is tight

    def test_other_ip_tags_become_definitions(self) -> None:
        (dl,) = blocks(parse('.IP "\\fBFOO\\fR" 4\nan environment variable\n'), DefinitionList)
        assert inline_shape(dl.items[0][0].content) == "B[FOO]"

    def test_rs_nests_inside_a_description(self) -> None:
        doc = parse(".TP\n.B \\-W\nwarnings:\n.RS\n.TP\n.B default\nonce\n.RE\n.TP\n.B \\-x\nskip\n")
        (dl,) = blocks(doc, DefinitionList)
        assert [inline_shape(term.content) for term, _ in dl.items] == ["B[-W]", "B[-x]"]
        nested = dl.items[0][1][0].content
        assert isinstance(nested[0], Paragraph) and isinstance(nested[1], DefinitionList)

    def test_rs_outside_a_list_is_a_block_quote(self) -> None:
        (quote,) = blocks(parse("intro\n.RS\nindented\n.RE\n"), BlockQuote)
        assert inline_shape(quote.children[0].content) == "indented"

    def test_unbalanced_rs_is_closed_at_the_end(self) -> None:
        doc = parse("intro\n.RS\nindented\n")
        assert len(blocks(doc, BlockQuote)) == 1

    def test_no_fill_becomes_code_block(self) -> None:
        doc = parse(".nf\n.B bold line\n  indented \\fIx\\fR\n\nlast\n.fi\nafter\n")
        (code,) = blocks(doc, CodeBlock)
        assert code.content == "bold line\n  indented x\n\nlast"
        assert first_paragraph(doc) == "after"

    def test_example_macros_become_code_block(self) -> None:
        (code,) = blocks(parse(".EX\n$ ls \\-l\n.EE\n"), CodeBlock)
        assert code.content == "$ ls -l"

    def test_table(self) -> None:
        source = ".TS\ntab(;);\nlB cB rB\nl c r.\nName;Size;Count\n_\nfoo;\\fBbig\\fR;3\nbar;small\n.TE\n"
        (table,) = blocks(parse(source), Table)
        assert table.header is not None
        assert [inline_shape(cell.content) for cell in table.header.cells] == ["Name", "Size", "Count"]
        assert [[inline_shape(cell.content) for cell in row.cells] for row in table.rows] == [
            ["foo", "B[big]", "3"],
            ["bar", "small", ""],
        ]
        assert table.alignments == ["left", "center", "right"]

    def test_table_text_blocks_are_cells(self) -> None:
        # The ATTRIBUTES-table shape: a T{ T} block with requests, then more fields
        # on the T} line, and a block in the middle of a row.
        source = (
            ".TS\nallbox;\nlbx lb lb\nl l l.\nInterface\tAttribute\tValue\n"
            "T{\n.na\n.nh\n.BR printf (),\n.BR fprintf ()\nT}\tThread safety\tMT-Safe\n"
            "key\tT{\nsee\n.UR https://example.com\nthe docs\n.UE .\nT}\tend\n"
            "x\tT{\none\n.br\ntwo\nT}\ty\n.TE\n"
        )
        (table,) = blocks(parse(source), Table)
        assert [[inline_shape(cell.content) for cell in row.cells] for row in table.rows] == [
            ["B[printf](), B[fprintf]()", "Thread safety", "MT-Safe"],
            ["key", "see L<https://example.com>[the docs].", "end"],
            ["x", "oneBRtwo", "y"],
        ]

    def test_table_text_block_keeps_nested_list_text(self) -> None:
        source = (
            ".TS\nl l.\nh1\th2\n"
            "T{\n.TP\n.B \\-a\nall entries\n.TP\n.B \\-l\nlong form\nT}\tT{\n.IP \\(bu 2\none\n.IP \\(bu 2\ntwo\nT}\n"
            ".TE\n"
        )
        (table,) = blocks(parse(source), Table)
        assert [inline_shape(cell.content) for cell in table.rows[0].cells] == [
            "B[-a] all entries B[-l] long form",
            "one two",
        ]

    def test_table_format_change_is_skipped(self) -> None:
        source = ".TS\nl l.\na\tb\n.T&\nc s.\nspanning\n.T&\nl l.\nc\td\n.TE\n"
        (table,) = blocks(parse(source), Table)
        assert [[inline_shape(cell.content) for cell in row.cells] for row in table.rows] == [
            ["spanning", ""],
            ["c", "d"],
        ]

    def test_table_cells_carry_the_column_alignment(self) -> None:
        (table,) = blocks(parse(".TS\nl r.\na\tb\nc\td\n.TE\n"), Table)
        assert [cell.alignment for cell in table.rows[0].cells] == ["left", "right"]


class TestRoffRequests:
    """The request language around the macros."""

    def test_macro_definitions_are_skipped(self) -> None:
        doc = parse(".de XX\nhidden text\n..\n.ig\nignored\n..\nshown\n")
        assert [inline_shape(p.content) for p in blocks(doc, Paragraph)] == ["shown"]

    def test_conditionals(self) -> None:
        source = (
            ".if n nroff\n"
            ".if t troff\n"
            ".ie t \\{\\\n"
            "troff branch\n"
            ".\\}\n"
            ".el \\{\\\n"
            "else branch\n"
            ".\\}\n"
            ".if !d XX defined\n"
        )
        assert first_paragraph(parse(source)) == "nroff else branch"

    def test_pod2man_page(self) -> None:
        doc = parse(POD2MAN_PAGE)
        assert doc.metadata["title"] == "FOO(1)"
        assert doc.metadata["description"] == "frobnicate the widgets"
        (code,) = blocks(doc, CodeBlock)
        assert code.content == "    use Foo;\n    my $x = Foo->new;"
        description = [p for p in blocks(doc, Paragraph) if "Call" in inline_shape(p.content)][0]
        # In nroff mode pod2man's \*(C` and \*(C' strings are double quotes.
        assert inline_shape(description.content) == 'Call C["frob"] to B[frobnicate], it\'s easy.'
        (dl,) = blocks(doc, DefinitionList)
        assert inline_shape(dl.items[0][0].content) == "B[--verbose]"
        (bullets,) = blocks(doc, List)
        assert len(bullets.items) == 2

    def test_so_include_is_reported(self, caplog: pytest.LogCaptureFixture) -> None:
        with caplog.at_level(logging.WARNING, logger="all2md.parsers.man"):
            parse(".TH X 1\n.so man7/other.7\n")
        assert "includes another file" in caplog.text

    def test_mdoc_is_reported(self, caplog: pytest.LogCaptureFixture) -> None:
        with caplog.at_level(logging.WARNING, logger="all2md.parsers.man"):
            parse(".Dd January 1, 2024\n.Dt LS 1\n.Sh NAME\n")
        assert "mdoc" in caplog.text

    def test_ig_with_an_end_marker_skips_past_dot_dot(self) -> None:
        # .ig XX ends at .XX, not at the first "..", which is just ignored text.
        doc = parse(".TH X 1\n.ig XX\nhidden\n..\nstill hidden\n.XX\nshown\n")
        assert [inline_shape(p.content) for p in blocks(doc, Paragraph)] == ["shown"]

    @pytest.mark.parametrize(
        "escape",
        ["\\[u110000]", "\\[char1114112]", "\\N'99999999'", "\\[uD800]", "\\N'\u00b2'"],
        ids=["u-past-unicode", "char-past-unicode", "N-past-unicode", "surrogate", "N-non-ascii-digit"],
    )
    def test_out_of_range_character_references_do_not_raise(self, escape: str) -> None:
        text = first_paragraph(parse(f"a {escape} b\n"))
        assert text.startswith("a ") and text.endswith(" b")
        text.encode("utf-8")  # no lone surrogate survives
        assert all(ord(ch) < 0xD800 or ord(ch) > 0xDFFF for ch in text)

    def test_unknown_macros_are_ignored(self) -> None:
        assert first_paragraph(parse(".XYZ some args\ntext\n")) == "text"


class TestEndToEnd:
    """Whole pages through to_markdown."""

    def test_to_markdown(self) -> None:
        source = (
            '.TH LS 1 2024-03-01 "GNU coreutils" "User Commands"\n'
            ".SH NAME\nls \\- list directory contents\n"
            ".SH OPTIONS\n.TP\n\\fB\\-a\\fR, \\fB\\-\\-all\\fR\ndo not ignore entries starting with .\n"
            ".SH EXAMPLES\n.EX\n$ ls \\-la\n.EE\n"
        )
        result = to_markdown(source.encode(), source_format="man")
        assert "# LS(1)" in result
        assert "## OPTIONS" in result
        assert "**-a**, **--all**\n: do not ignore entries starting with ." in result
        assert "```\n$ ls -la\n```" in result

    def test_markdown_round_trips_the_formatting(self) -> None:
        assert markdown(".TH X 1\n.SH NAME\nx \\- \\fBbold\\fR and \\fIitalic\\fR\n").endswith(
            "x - **bold** and *italic*"
        )
