"""Generated converter manifest — DO NOT EDIT BY HAND.

This module lists the built-in converter metadata as pure literals so the
registry can populate format-detection metadata without importing every parser
and renderer module at startup. Parser/renderer/options classes and content
detectors are imported lazily on first use.

Regenerate with:
    python scripts/generate_converter_manifest.py --update
"""

# ruff: noqa: E501  (generated file: long literal extension/mime/message lines)

from __future__ import annotations

from all2md.converter_metadata import ConverterMetadata

_MANIFEST_RECORDS: list[ConverterMetadata] = [
    ConverterMetadata(
        format_name="archive",
        extensions=[".tar", ".tgz", ".tar.gz", ".tbz2", ".tb2", ".tar.bz2", ".txz", ".tar.xz", ".7z", ".rar"],
        mime_types=[
            "application/x-tar",
            "application/gzip",
            "application/x-gzip",
            "application/x-bzip2",
            "application/x-xz",
            "application/x-7z-compressed",
            "application/vnd.rar",
            "application/x-rar-compressed",
        ],
        magic_bytes=[
            (b"\x1f\x8b", 0),
            (b"BZ", 0),
            (b"\xfd7zXZ\x00", 0),
            (b"7z\xbc\xaf'\x1c", 0),
            (b"Rar!\x1a\x07\x00", 0),
            (b"Rar!\x1a\x07\x01\x00", 0),
        ],
        parser_class="all2md.parsers.archive.ArchiveToAstConverter",
        optional_packages=[("py7zr", ">=0.22.0"), ("rarfile", ">=4.2")],
        parser_options_class="all2md.options.archive.ArchiveOptions",
        description="Extract and convert files from TAR, 7Z, and RAR archives",
        priority=3,
    ),
    ConverterMetadata(
        format_name="asciidoc",
        extensions=[".adoc", ".asciidoc", ".asc"],
        mime_types=["text/asciidoc", "text/x-asciidoc"],
        parser_class="all2md.parsers.asciidoc.AsciiDocParser",
        renderer_class="all2md.renderers.asciidoc.AsciiDocRenderer",
        renders_as_string=True,
        parser_options_class="all2md.options.asciidoc.AsciiDocOptions",
        renderer_options_class="all2md.options.asciidoc.AsciiDocRendererOptions",
        description="Parse and render AsciiDoc format",
        priority=10,
    ),
    ConverterMetadata(
        format_name="ast",
        extensions=[".ast"],
        mime_types=["application/json"],
        content_detector_path="all2md.parsers.ast_json._is_ast_json_content",
        parser_class="all2md.parsers.ast_json.AstJsonParser",
        renderer_class="all2md.renderers.ast_json.AstJsonRenderer",
        renders_as_string=True,
        parser_options_class="all2md.options.ast_json.AstJsonParserOptions",
        renderer_options_class="all2md.options.ast_json.AstJsonRendererOptions",
        description="Parse and render documents in JSON-serialized AST format for programmatic access.",
        priority=5,
    ),
    ConverterMetadata(
        format_name="bbcode",
        extensions=[".bbcode", ".bb"],
        mime_types=["text/x-bbcode"],
        parser_class="all2md.parsers.bbcode.BBCodeParser",
        parser_options_class="all2md.options.bbcode.BBCodeParserOptions",
        description="Parse BBCode bulletin board markup to AST",
        priority=10,
    ),
    ConverterMetadata(
        format_name="chm",
        extensions=[".chm"],
        mime_types=["application/vnd.ms-htmlhelp"],
        magic_bytes=[(b"ITSF", 0)],
        parser_class="all2md.parsers.chm.ChmParser",
        parser_required_packages=[("pychm", "chm", "")],
        import_error_message="CHM conversion requires 'pychm'. Note: pychm also requires the CHMLib C library to be installed. Install with: pip install pychm",
        parser_options_class="all2md.options.chm.ChmOptions",
        description="Convert Microsoft Compiled HTML Help (CHM) files to AST",
        priority=5,
    ),
    ConverterMetadata(
        format_name="csv",
        extensions=[".csv", ".tsv"],
        mime_types=["text/csv", "application/csv", "text/tab-separated-values"],
        content_detector_path="all2md.parsers.csv._detect_csv_tsv_content",
        parser_class="all2md.parsers.csv.CsvToAstConverter",
        renderer_class="all2md.renderers.csv.CsvRenderer",
        renders_as_string=True,
        import_error_message="CSV/TSV conversion uses Python standard library (no dependencies)",
        parser_options_class="all2md.options.csv.CsvOptions",
        renderer_options_class="all2md.options.csv.CsvRendererOptions",
        description="Convert CSV and TSV files to/from Markdown tables",
        priority=6,
    ),
    ConverterMetadata(
        format_name="docx",
        extensions=[".docx"],
        mime_types=["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.docx.DocxToAstConverter",
        renderer_class="all2md.renderers.docx.DocxRenderer",
        parser_required_packages=[("python-docx", "docx", "")],
        renderer_required_packages=[("python-docx", "docx", ">=1.2.0")],
        import_error_message="DOCX conversion requires 'python-docx'. Install with: pip install python-docx",
        parser_options_class="all2md.options.docx.DocxOptions",
        renderer_options_class="all2md.options.docx.DocxRendererOptions",
        description="Convert Microsoft Word DOCX documents to/from AST",
        priority=8,
    ),
    ConverterMetadata(
        format_name="dokuwiki",
        extensions=[".doku", ".dokuwiki"],
        mime_types=["text/plain"],
        parser_class="all2md.parsers.dokuwiki.DokuWikiParser",
        renderer_class="all2md.renderers.dokuwiki.DokuWikiRenderer",
        renders_as_string=True,
        parser_options_class="all2md.options.dokuwiki.DokuWikiParserOptions",
        renderer_options_class="all2md.options.dokuwiki.DokuWikiOptions",
        description="Parse and render DokuWiki markup",
        priority=10,
    ),
    ConverterMetadata(
        format_name="dokuwiki",
        extensions=[".doku", ".dokuwiki"],
        mime_types=["text/plain"],
        parser_class="all2md.parsers.dokuwiki.DokuWikiParser",
        renderer_class="all2md.renderers.dokuwiki.DokuWikiRenderer",
        renders_as_string=True,
        parser_options_class="all2md.options.dokuwiki.DokuWikiParserOptions",
        renderer_options_class="all2md.options.dokuwiki.DokuWikiOptions",
        description="Parse and render DokuWiki markup",
        priority=10,
    ),
    ConverterMetadata(
        format_name="eml",
        extensions=[".eml", ".msg"],
        mime_types=["message/rfc822"],
        magic_bytes=[
            (b"Return-Path:", 0),
            (b"Received:", 0),
            (b"From:", 0),
            (b"To:", 0),
            (b"Subject:", 0),
            (b"Content-Type:", 0),
            (b"MIME-Version:", 0),
        ],
        parser_class="all2md.parsers.eml.EmlToAstConverter",
        parser_options_class="all2md.options.eml.EmlOptions",
        description="Convert email messages to Markdown",
        priority=6,
    ),
    ConverterMetadata(
        format_name="enex",
        extensions=[".enex"],
        mime_types=["application/enex+xml"],
        magic_bytes=[(b"<?xml", 0), (b"<en-export", 0)],
        parser_class="all2md.parsers.enex.EnexToAstConverter",
        parser_options_class="all2md.options.enex.EnexOptions",
        description="Convert Evernote ENEX exports to Markdown",
        priority=6,
    ),
    ConverterMetadata(
        format_name="epub",
        extensions=[".epub"],
        mime_types=["application/epub+zip"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.epub.EpubToAstConverter",
        renderer_class="all2md.renderers.epub.EpubRenderer",
        parser_required_packages=[("ebooklib", "ebooklib", "")],
        renderer_required_packages=[("ebooklib", "ebooklib", ">=0.17")],
        import_error_message="ePub conversion requires 'ebooklib'. Install with: pip install ebooklib",
        parser_options_class="all2md.options.epub.EpubOptions",
        renderer_options_class="all2md.options.epub.EpubRendererOptions",
        description="Electronic Publication (EPUB) format",
        priority=8,
    ),
    ConverterMetadata(
        format_name="fb2",
        extensions=[".fb2"],
        mime_types=["application/x-fictionbook+xml", "text/xml"],
        magic_bytes=[(b"<?xml", 0)],
        content_detector_path="all2md.parsers.fb2._is_fb2_content",
        parser_class="all2md.parsers.fb2.Fb2ToAstConverter",
        parser_options_class="all2md.options.fb2.Fb2Options",
        description="FictionBook 2.0 ebook format",
        priority=6,
    ),
    ConverterMetadata(
        format_name="html",
        extensions=[".html", ".htm", ".xhtml"],
        mime_types=["text/html", "application/xhtml+xml"],
        magic_bytes=[(b"<!DOCTYPE html", 0), (b"<!doctype html", 0), (b"<html", 0), (b"<HTML", 0)],
        parser_class="all2md.parsers.html.HtmlToAstConverter",
        renderer_class="all2md.renderers.html.HtmlRenderer",
        parser_required_packages=[("beautifulsoup4", "bs4", ">=4.14.2")],
        renders_as_string=True,
        optional_packages=[("readability-lxml", "readability")],
        parser_options_class="all2md.options.html.HtmlOptions",
        renderer_options_class="all2md.options.html.HtmlRendererOptions",
        description="Convert HTML documents to/from AST",
        priority=5,
    ),
    ConverterMetadata(
        format_name="ini",
        extensions=[".ini", ".cfg", ".conf"],
        mime_types=["text/plain"],
        content_detector_path="all2md.parsers.ini._detect_ini_content",
        parser_class="all2md.parsers.ini.IniParser",
        renderer_class="all2md.renderers.ini.IniRenderer",
        renders_as_string=True,
        import_error_message="INI conversion uses Python standard library (no dependencies)",
        parser_options_class="all2md.options.ini.IniParserOptions",
        renderer_options_class="all2md.options.ini.IniRendererOptions",
        description="Convert INI config files to/from a fenced code block (default) or a structured document",
        priority=10,
    ),
    ConverterMetadata(
        format_name="ipynb",
        extensions=[".ipynb"],
        mime_types=["application/json"],
        magic_bytes=[(b'{"cells":', 0), (b'{ "cells":', 0)],
        parser_class="all2md.parsers.ipynb.IpynbToAstConverter",
        renderer_class="all2md.renderers.ipynb.IpynbRenderer",
        parser_options_class="all2md.options.ipynb.IpynbOptions",
        renderer_options_class="all2md.options.ipynb.IpynbRendererOptions",
        description="Convert Jupyter Notebooks between AST and .ipynb",
        priority=7,
    ),
    ConverterMetadata(
        format_name="jinja",
        renderer_class="all2md.renderers.jinja.JinjaRenderer",
        renderer_required_packages=[("jinja2", "jinja2", ">=3.1.0")],
        renders_as_string=True,
        import_error_message="Jinja2 template renderer requires jinja2 package. Install with: pip install jinja2>=3.0.0",
        renderer_options_class="all2md.options.jinja.JinjaRendererOptions",
        description="Generic Jinja2 template-based renderer for custom output formats",
        priority=10,
    ),
    ConverterMetadata(
        format_name="json",
        extensions=[".json"],
        mime_types=["application/json", "text/json"],
        content_detector_path="all2md.parsers.json._detect_json_content",
        parser_class="all2md.parsers.json.JsonParser",
        renderer_class="all2md.renderers.json.JsonRenderer",
        renders_as_string=True,
        import_error_message="JSON conversion uses Python standard library (no dependencies)",
        parser_options_class="all2md.options.json.JsonParserOptions",
        renderer_options_class="all2md.options.json.JsonRendererOptions",
        description="Convert JSON to/from a fenced code block (default) or a structured document",
        priority=10,
    ),
    ConverterMetadata(
        format_name="latex",
        extensions=[".tex", ".latex"],
        mime_types=["text/x-tex", "application/x-tex", "application/x-latex"],
        parser_class="all2md.parsers.latex.LatexParser",
        renderer_class="all2md.renderers.latex.LatexRenderer",
        parser_required_packages=[("pylatexenc", "pylatexenc", ">=2.10")],
        renders_as_string=True,
        import_error_message="LaTeX parsing requires the 'pylatexenc' package. Install it with: pip install pylatexenc",
        parser_options_class="all2md.options.latex.LatexOptions",
        renderer_options_class="all2md.options.latex.LatexRendererOptions",
        description="Parse and render LaTeX format",
        priority=10,
    ),
    ConverterMetadata(
        format_name="markdown",
        extensions=[".md", ".markdown", ".mdown", ".mkd", ".mkdn"],
        mime_types=["text/markdown", "text/x-markdown"],
        parser_class="all2md.parsers.markdown.MarkdownToAstConverter",
        renderer_class="all2md.renderers.markdown.MarkdownRenderer",
        parser_required_packages=[("mistune", "mistune", ">=3.0.0")],
        renders_as_string=True,
        import_error_message="Markdown parsing requires 'mistune'. Install with: pip install 'all2md[markdown]'",
        parser_options_class="all2md.options.markdown.MarkdownParserOptions",
        renderer_options_class="all2md.options.markdown.MarkdownRendererOptions",
        description="Parse Markdown to AST and render AST to Markdown",
        priority=10,
    ),
    ConverterMetadata(
        format_name="mbox",
        extensions=[".mbox", ".mbx"],
        mime_types=["application/mbox"],
        magic_bytes=[(b"From ", 0)],
        parser_class="all2md.parsers.mbox.MboxToAstConverter",
        parser_options_class="all2md.options.mbox.MboxOptions",
        description="Convert Unix mailbox archives (mbox, maildir, etc.) to Markdown",
        priority=5,
    ),
    ConverterMetadata(
        format_name="mediawiki",
        extensions=[".wiki", ".mw"],
        mime_types=["text/x-wiki"],
        parser_class="all2md.parsers.mediawiki.MediaWikiParser",
        renderer_class="all2md.renderers.mediawiki.MediaWikiRenderer",
        parser_required_packages=[("mwparserfromhell", "mwparserfromhell", "")],
        renders_as_string=True,
        import_error_message="MediaWiki parsing requires 'mwparserfromhell'. Install with: pip install 'all2md[mediawiki]'",
        parser_options_class="all2md.options.mediawiki.MediaWikiParserOptions",
        renderer_options_class="all2md.options.mediawiki.MediaWikiOptions",
        description="Parse MediaWiki/WikiText to AST and render AST to MediaWiki",
        priority=10,
    ),
    ConverterMetadata(
        format_name="mediawiki",
        extensions=[".wiki", ".mw"],
        mime_types=["text/x-wiki"],
        renderer_class="all2md.renderers.mediawiki.MediaWikiRenderer",
        renders_as_string=True,
        renderer_options_class="all2md.options.mediawiki.MediaWikiOptions",
        description="Render AST to MediaWiki markup.",
        priority=5,
    ),
    ConverterMetadata(
        format_name="mhtml",
        extensions=[".mhtml", ".mht"],
        mime_types=["multipart/related", "message/rfc822"],
        magic_bytes=[(b"MIME-Version:", 0)],
        parser_class="all2md.parsers.mhtml.MhtmlToAstConverter",
        parser_required_packages=[("beautifulsoup4", "bs4", "")],
        import_error_message="MHTML conversion requires 'beautifulsoup4'. Install with: pip install beautifulsoup4",
        parser_options_class="all2md.options.mhtml.MhtmlOptions",
        description="Convert MHTML web archives to Markdown",
        priority=5,
    ),
    ConverterMetadata(
        format_name="odp",
        extensions=[".odp"],
        mime_types=["application/vnd.oasis.opendocument.presentation"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.odp.OdpToAstConverter",
        renderer_class="all2md.renderers.odp.OdpRenderer",
        parser_required_packages=[("odfpy", "odf", "")],
        renderer_required_packages=[("odfpy", "odf", "")],
        import_error_message="ODP conversion requires 'odfpy'. Install with: pip install odfpy",
        parser_options_class="all2md.options.odp.OdpOptions",
        renderer_options_class="all2md.options.OdpRendererOptions",
        description="Convert OpenDocument Presentation files to/from Markdown",
        priority=5,
    ),
    ConverterMetadata(
        format_name="ods",
        extensions=[".ods"],
        mime_types=["application/vnd.oasis.opendocument.spreadsheet"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.ods_spreadsheet.OdsSpreadsheetToAstConverter",
        parser_required_packages=[("odfpy", "odf", "")],
        import_error_message="ODS conversion requires 'odfpy'. Install with: pip install odfpy",
        parser_options_class="all2md.options.ods.OdsSpreadsheetOptions",
        description="Convert OpenDocument Spreadsheet files to Markdown tables",
        priority=6,
    ),
    ConverterMetadata(
        format_name="odt",
        extensions=[".odt"],
        mime_types=["application/vnd.oasis.opendocument.text"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.odt.OdtToAstConverter",
        renderer_class="all2md.renderers.odt.OdtRenderer",
        parser_required_packages=[("odfpy", "odf", "")],
        renderer_required_packages=[("odfpy", "odf", "")],
        import_error_message="ODT conversion requires 'odfpy'. Install with: pip install odfpy",
        parser_options_class="all2md.options.odt.OdtOptions",
        renderer_options_class="all2md.options.OdtRendererOptions",
        description="Convert OpenDocument Text files to/from Markdown",
        priority=5,
    ),
    ConverterMetadata(
        format_name="openapi",
        extensions=[".yaml", ".yml", ".json"],
        mime_types=["application/vnd.oai.openapi", "application/vnd.oai.openapi+json", "application/x-yaml"],
        content_detector_path="all2md.parsers.openapi._is_openapi_content",
        parser_class="all2md.parsers.openapi.OpenApiParser",
        parser_required_packages=[("PyYAML", "yaml", ">=5.1")],
        import_error_message="OpenAPI parsing requires 'PyYAML'. Install with: pip install 'all2md[openapi]'",
        parser_options_class="all2md.options.openapi.OpenApiParserOptions",
        description="Parse OpenAPI/Swagger specifications (2.0 and 3.x) to Markdown",
        priority=7,
    ),
    ConverterMetadata(
        format_name="org",
        extensions=[".org"],
        mime_types=["text/org", "text/x-org"],
        parser_class="all2md.parsers.org.OrgParser",
        renderer_class="all2md.renderers.org.OrgRenderer",
        parser_required_packages=[("orgparse", "orgparse", "")],
        renders_as_string=True,
        import_error_message="Org-Mode parsing requires 'orgparse'. Install with: pip install 'all2md[org]'",
        parser_options_class="all2md.options.org.OrgParserOptions",
        renderer_options_class="all2md.options.org.OrgRendererOptions",
        description="Parse Org-Mode to AST and render AST to Org-Mode",
        priority=10,
    ),
    ConverterMetadata(
        format_name="outlook",
        extensions=[".msg", ".pst", ".ost"],
        mime_types=["application/vnd.ms-outlook"],
        magic_bytes=[(b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1", 0), (b"!BDN", 0)],
        parser_class="all2md.parsers.outlook.OutlookToAstConverter",
        parser_required_packages=[("extract-msg", "extract_msg", "")],
        parser_options_class="all2md.options.outlook.OutlookOptions",
        description="Convert Microsoft Outlook MSG, PST, and OST files to Markdown",
        priority=5,
    ),
    ConverterMetadata(
        format_name="pdf",
        extensions=[".pdf"],
        mime_types=["application/pdf"],
        magic_bytes=[(b"%PDF", 0)],
        parser_class="all2md.parsers.pdf.PdfToAstConverter",
        renderer_class="all2md.renderers.pdf.PdfRenderer",
        parser_required_packages=[("pymupdf", "fitz", ">=1.26.4")],
        renderer_required_packages=[("reportlab", "reportlab", ">=4.0.0")],
        optional_packages=[("pytesseract", "pytesseract"), ("Pillow", "PIL")],
        import_error_message="PDF conversion requires 'PyMuPDF'. Install with: pip install pymupdf",
        parser_options_class="all2md.options.pdf.PdfOptions",
        renderer_options_class="all2md.options.pdf.PdfRendererOptions",
        description="Convert PDF documents to/from AST with table detection and optional OCR support",
        priority=10,
    ),
    ConverterMetadata(
        format_name="plaintext",
        extensions=[".txt", ".text"],
        mime_types=["text/plain"],
        parser_class="all2md.parsers.plaintext.PlainTextToAstConverter",
        renderer_class="all2md.renderers.plaintext.PlainTextRenderer",
        renders_as_string=True,
        parser_options_class="all2md.options.plaintext.PlainTextParserOptions",
        renderer_options_class="all2md.options.plaintext.PlainTextOptions",
        description="Parse and render plain text files.",
        priority=1,
    ),
    ConverterMetadata(
        format_name="pptx",
        extensions=[".pptx"],
        mime_types=["application/vnd.openxmlformats-officedocument.presentationml.presentation"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.pptx.PptxToAstConverter",
        renderer_class="all2md.renderers.pptx.PptxRenderer",
        parser_required_packages=[("python-pptx", "pptx", "")],
        renderer_required_packages=[("python-pptx", "pptx", ">=0.6.21")],
        import_error_message="PPTX conversion requires 'python-pptx'. Install with: pip install python-pptx",
        parser_options_class="all2md.options.pptx.PptxOptions",
        renderer_options_class="all2md.options.pptx.PptxRendererOptions",
        description="Convert PowerPoint presentations to/from Markdown",
        priority=7,
    ),
    ConverterMetadata(
        format_name="rst",
        extensions=[".rst", ".rest"],
        mime_types=["text/x-rst", "text/prs.fallenstein.rst"],
        parser_class="all2md.parsers.rst.RestructuredTextParser",
        renderer_class="all2md.renderers.rst.RestructuredTextRenderer",
        parser_required_packages=[("docutils", "docutils", ">=0.18")],
        renders_as_string=True,
        import_error_message="RST parsing requires 'docutils'. Install with: pip install 'all2md[rst]'",
        parser_options_class="all2md.options.rst.RstParserOptions",
        renderer_options_class="all2md.options.rst.RstRendererOptions",
        description="Parse reStructuredText to AST and render AST to reStructuredText",
        priority=10,
    ),
    ConverterMetadata(
        format_name="rtf",
        extensions=[".rtf"],
        mime_types=["application/rtf", "text/rtf"],
        magic_bytes=[(b"{\\rtf", 0)],
        parser_class="all2md.parsers.rtf.RtfToAstConverter",
        renderer_class="all2md.renderers.rtf.RtfRenderer",
        parser_required_packages=[("pyth3", "pyth", ""), ("six", "six", ">=1.16.0")],
        renderer_required_packages=[("pyth3", "pyth", ""), ("six", "six", ">=1.16.0")],
        renders_as_string=True,
        import_error_message="RTF conversion requires 'pyth3' and 'six'. Install with: pip install pyth3 six",
        parser_options_class="all2md.options.rtf.RtfOptions",
        renderer_options_class="all2md.options.rtf.RtfRendererOptions",
        description="Convert Rich Text Format documents to Markdown",
        priority=4,
    ),
    ConverterMetadata(
        format_name="sourcecode",
        extensions=[
            ".py",
            ".pyx",
            ".pyi",
            ".js",
            ".mjs",
            ".cjs",
            ".jsx",
            ".ts",
            ".tsx",
            ".html",
            ".htm",
            ".xhtml",
            ".css",
            ".scss",
            ".sass",
            ".less",
            ".c",
            ".h",
            ".cpp",
            ".cxx",
            ".cc",
            ".hpp",
            ".hxx",
            ".hh",
            ".java",
            ".kt",
            ".kts",
            ".scala",
            ".groovy",
            ".cs",
            ".fs",
            ".vb",
            ".go",
            ".rs",
            ".swift",
            ".m",
            ".mm",
            ".php",
            ".rb",
            ".gemspec",
            ".rake",
            ".sh",
            ".bash",
            ".zsh",
            ".fish",
            ".csh",
            ".ksh",
            ".ps1",
            ".bat",
            ".cmd",
            ".lua",
            ".pl",
            ".pm",
            ".r",
            ".hs",
            ".erl",
            ".hrl",
            ".ex",
            ".exs",
            ".lisp",
            ".el",
            ".clj",
            ".elm",
            ".ml",
            ".f",
            ".f90",
            ".f95",
            ".for",
            ".json5",
            ".yaml",
            ".yml",
            ".toml",
            ".ini",
            ".conf",
            ".cfg",
            ".properties",
            ".xml",
            ".xsd",
            ".wsdl",
            ".svg",
            ".rss",
            ".atom",
            ".plist",
            ".xaml",
            ".md",
            ".markdown",
            ".mdown",
            ".mkd",
            ".mkdn",
            ".mdwn",
            ".mdx",
            ".rst",
            ".textile",
            ".adoc",
            ".asciidoc",
            ".sql",
            ".dockerfile",
            ".graphql",
            ".gql",
            ".proto",
            ".tf",
            ".hcl",
            ".nix",
            ".vim",
            ".gitignore",
            ".gitattributes",
            ".tex",
            ".bib",
            ".diff",
            ".patch",
            ".log",
        ],
        mime_types=[
            "text/plain",
            "text/x-python",
            "text/x-java-source",
            "text/x-c",
            "text/x-c++src",
            "text/x-csharp",
            "text/x-javascript",
            "text/x-typescript",
            "text/x-go",
            "text/x-rust",
            "text/x-swift",
            "text/x-php",
            "text/x-ruby",
            "text/x-perl",
            "text/x-shellscript",
            "text/x-sql",
            "application/x-javascript",
            "application/javascript",
            "application/typescript",
            "application/x-python-code",
            "application/x-java-source",
            "application/x-csh",
            "application/x-sh",
            "application/x-shellscript",
        ],
        parser_class="all2md.parsers.sourcecode.SourceCodeToAstConverter",
        parser_options_class="all2md.options.sourcecode.SourceCodeOptions",
        description="Convert source code files to Markdown with syntax highlighting",
        priority=1,
    ),
    ConverterMetadata(
        format_name="textile",
        extensions=[".textile"],
        mime_types=["text/x-textile"],
        parser_class="all2md.parsers.textile.TextileParser",
        renderer_class="all2md.renderers.textile.TextileRenderer",
        parser_required_packages=[("textile", "textile", "")],
        renderer_required_packages=[("textile", "textile", "")],
        renders_as_string=True,
        parser_options_class="all2md.options.textile.TextileParserOptions",
        renderer_options_class="all2md.options.textile.TextileRendererOptions",
        description="Parse and render Textile markup format",
        priority=10,
    ),
    ConverterMetadata(
        format_name="textile",
        extensions=[".textile"],
        mime_types=["text/x-textile"],
        parser_class="all2md.parsers.textile.TextileParser",
        renderer_class="all2md.renderers.textile.TextileRenderer",
        parser_required_packages=[("textile", "textile", "")],
        renders_as_string=True,
        parser_options_class="all2md.options.textile.TextileParserOptions",
        renderer_options_class="all2md.options.textile.TextileRendererOptions",
        description="Parse and render Textile markup format",
        priority=10,
    ),
    ConverterMetadata(
        format_name="toml",
        extensions=[".toml"],
        mime_types=["application/toml", "text/toml"],
        content_detector_path="all2md.parsers.toml._detect_toml_content",
        parser_class="all2md.parsers.toml.TomlParser",
        renderer_class="all2md.renderers.toml.TomlRenderer",
        parser_required_packages=[("tomli-w", "tomli_w", ">=1.0.0")],
        renderer_required_packages=[("tomli-w", "tomli_w", ">=1.0.0")],
        renders_as_string=True,
        import_error_message="TOML conversion requires tomli and tomli-w (pip install tomli tomli-w)",
        parser_options_class="all2md.options.toml.TomlParserOptions",
        renderer_options_class="all2md.options.toml.TomlRendererOptions",
        description="Convert TOML to/from a fenced code block (default) or a structured document",
        priority=10,
    ),
    ConverterMetadata(
        format_name="webarchive",
        extensions=[".webarchive"],
        mime_types=["application/x-webarchive"],
        magic_bytes=[(b"bplist00", 0)],
        parser_class="all2md.parsers.webarchive.WebArchiveToAstConverter",
        parser_required_packages=[("beautifulsoup4", "bs4", "")],
        import_error_message="WebArchive conversion requires 'beautifulsoup4'. Install with: pip install beautifulsoup4",
        parser_options_class="all2md.options.webarchive.WebArchiveOptions",
        description="Convert Safari WebArchive files to Markdown",
        priority=5,
    ),
    ConverterMetadata(
        format_name="xlsx",
        extensions=[".xlsx"],
        mime_types=["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.xlsx.XlsxToAstConverter",
        parser_required_packages=[("openpyxl", "openpyxl", "")],
        import_error_message="XLSX conversion requires 'openpyxl'. Install with: pip install openpyxl",
        parser_options_class="all2md.options.xlsx.XlsxOptions",
        description="Convert Excel XLSX files to Markdown tables",
        priority=6,
    ),
    ConverterMetadata(
        format_name="yaml",
        extensions=[".yaml", ".yml"],
        mime_types=["application/x-yaml", "text/yaml", "text/x-yaml"],
        content_detector_path="all2md.parsers.yaml._detect_yaml_content",
        parser_class="all2md.parsers.yaml.YamlParser",
        renderer_class="all2md.renderers.yaml.YamlRenderer",
        parser_required_packages=[("pyyaml", "yaml", ">=6.0")],
        renderer_required_packages=[("pyyaml", "yaml", ">=6.0")],
        renders_as_string=True,
        import_error_message="YAML conversion requires PyYAML (pip install pyyaml)",
        parser_options_class="all2md.options.yaml.YamlParserOptions",
        renderer_options_class="all2md.options.yaml.YamlRendererOptions",
        description="Convert YAML to/from a fenced code block (default) or a structured document",
        priority=5,
    ),
    ConverterMetadata(
        format_name="zip",
        extensions=[".zip"],
        mime_types=["application/zip"],
        magic_bytes=[(b"PK\x03\x04", 0)],
        parser_class="all2md.parsers.zip.ZipToAstConverter",
        parser_options_class="all2md.options.zip.ZipOptions",
        description="Extract and convert files from ZIP archives",
        priority=3,
    ),
]


def get_manifest_records() -> list[ConverterMetadata]:
    """Return the built-in converter metadata records (fresh list).

    A new list of the shared record instances is returned so callers may sort
    or filter without mutating the module-level list.
    """
    return list(_MANIFEST_RECORDS)
