"""Demo script for VCS document converter.

This script demonstrates the key features of the VCS converter:
- Converting binary documents to markdown
- Batch processing
- Bidirectional conversion
- Metadata preservation
"""

import sys
import tempfile
from pathlib import Path

from docx import Document as DocxDocument
from docx.shared import Inches, Pt

try:
    from vcs_converter import VCSConverter
except ImportError:
    print("Error: Run this script from the vcs-converter directory")
    sys.exit(1)


def create_sample_docx(output_path: Path) -> None:
    """Create a sample DOCX document for demonstration.

    Parameters
    ----------
    output_path : Path
        Where to save the document
    """
    doc = DocxDocument()

    # Add title
    title = doc.add_heading("Sample Document for VCS Testing", 0)

    # Add introduction
    intro = doc.add_paragraph(
        "This is a sample document created to demonstrate the VCS document "
        "converter. It contains various formatting elements to test the "
        "conversion process."
    )

    # Add section
    doc.add_heading("Features", 1)

    # Add list
    doc.add_paragraph("Bold text", style="List Bullet").runs[0].bold = True
    doc.add_paragraph("Italic text", style="List Bullet").runs[0].italic = True
    doc.add_paragraph("Underlined text", style="List Bullet").runs[0].underline = True

    # Add table
    doc.add_heading("Sample Table", 2)
    table = doc.add_table(rows=3, cols=3)
    table.style = "Light Grid Accent 1"

    # Fill table
    headers = ["Feature", "Status", "Notes"]
    for idx, header in enumerate(headers):
        cell = table.rows[0].cells[idx]
        cell.text = header
        cell.paragraphs[0].runs[0].bold = True

    data = [
        ["Conversion", "Working", "All formats supported"],
        ["Metadata", "Working", "JSON format"],
    ]

    for row_idx, row_data in enumerate(data, start=1):
        for col_idx, cell_text in enumerate(row_data):
            table.rows[row_idx].cells[col_idx].text = cell_text

    # Add code block
    doc.add_heading("Code Example", 2)
    code_para = doc.add_paragraph("git commit -m 'Update documentation'")
    code_para.style = "Intense Quote"

    # Add footer
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by VCS Converter Demo")
    footer.runs[0].italic = True
    footer.runs[0].font.size = Pt(9)

    # Save
    doc.save(str(output_path))
    print(f"Created sample document: {output_path}")


def demo_basic_conversion() -> None:
    """Demonstrate basic document conversion."""
    print("\n" + "=" * 70)
    print("DEMO 1: Basic Conversion (Binary to Markdown)")
    print("=" * 70)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        # Create sample document
        docx_path = tmpdir / "sample.docx"
        create_sample_docx(docx_path)

        # Initialize converter
        converter = VCSConverter()
        converter.markdown_dir = tmpdir / ".vcs-docs"

        # Convert to markdown
        print("\nConverting to markdown...")
        md_path, metadata_path = converter.convert_to_markdown(docx_path)

        print(f"\nGenerated files:")
        print(f"  - Markdown: {md_path}")
        print(f"  - Metadata: {metadata_path}")

        # Show markdown content
        print("\nMarkdown content (first 500 chars):")
        print("-" * 70)
        with open(md_path, encoding="utf-8") as f:
            content = f.read()
            print(content[:500])
            if len(content) > 500:
                print("...")
        print("-" * 70)

        # Show metadata
        print("\nMetadata:")
        print("-" * 70)
        if metadata_path and metadata_path.exists():
            with open(metadata_path, encoding="utf-8") as f:
                print(f.read())
        print("-" * 70)


def demo_batch_processing() -> None:
    """Demonstrate batch processing of multiple documents."""
    print("\n" + "=" * 70)
    print("DEMO 2: Batch Processing")
    print("=" * 70)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        # Create multiple sample documents
        docs_dir = tmpdir / "docs"
        docs_dir.mkdir()

        documents = ["report.docx", "presentation.docx", "notes.docx"]

        for doc_name in documents:
            doc_path = docs_dir / doc_name
            create_sample_docx(doc_path)

        # Initialize converter
        converter = VCSConverter()
        converter.markdown_dir = tmpdir / ".vcs-docs"

        # Batch convert
        print("\nScanning for documents...")
        found_docs = converter.scan_repository(tmpdir)
        print(f"Found {len(found_docs)} document(s)")

        print("\nBatch converting...")
        converter.batch_convert(tmpdir)

        print("\nGenerated markdown files:")
        for md_file in converter.markdown_dir.rglob("*.vcs.md"):
            print(f"  - {md_file.relative_to(tmpdir)}")


def demo_bidirectional_conversion() -> None:
    """Demonstrate bidirectional conversion."""
    print("\n" + "=" * 70)
    print("DEMO 3: Bidirectional Conversion (Markdown back to Binary)")
    print("=" * 70)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        # Create original document
        original_docx = tmpdir / "original.docx"
        create_sample_docx(original_docx)

        # Initialize converter
        converter = VCSConverter()
        converter.markdown_dir = tmpdir / ".vcs-docs"

        # Convert to markdown
        print("\nStep 1: Converting original DOCX to markdown...")
        md_path, metadata_path = converter.convert_to_markdown(original_docx)

        # Simulate editing the markdown
        print("\nStep 2: Simulating markdown edit...")
        with open(md_path, encoding="utf-8") as f:
            content = f.read()

        modified_content = content.replace("Sample Document for VCS Testing", "EDITED: Sample Document for VCS Testing")

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(modified_content)

        print("Added 'EDITED:' prefix to title")

        # Convert back to DOCX
        print("\nStep 3: Converting markdown back to DOCX...")
        reconstructed_docx = tmpdir / "reconstructed.docx"
        converter.convert_to_binary(md_path, reconstructed_docx)

        print(f"\nReconstructed document: {reconstructed_docx}")
        print(f"Original size: {original_docx.stat().st_size} bytes")
        print(f"Reconstructed size: {reconstructed_docx.stat().st_size} bytes")


def demo_workflow_simulation() -> None:
    """Demonstrate a complete git workflow simulation."""
    print("\n" + "=" * 70)
    print("DEMO 4: Git Workflow Simulation")
    print("=" * 70)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)

        # Setup repository structure
        repo_dir = tmpdir / "my-project"
        repo_dir.mkdir()
        docs_dir = repo_dir / "docs"
        docs_dir.mkdir()

        # Create initial document (version 1)
        print("\nVersion 1: Creating initial document...")
        doc_v1 = docs_dir / "requirements.docx"
        create_sample_docx(doc_v1)

        # Initialize converter
        converter = VCSConverter()
        converter.markdown_dir = repo_dir / ".vcs-docs"

        # Convert version 1
        print("Converting v1 to markdown...")
        md_v1, _ = converter.convert_to_markdown(doc_v1)

        with open(md_v1, encoding="utf-8") as f:
            content_v1 = f.read()

        print(f"V1 markdown: {len(content_v1)} characters")

        # Simulate document edit (version 2)
        print("\nVersion 2: Updating document...")
        doc = DocxDocument(str(doc_v1))
        doc.add_paragraph("NEW REQUIREMENT: System must support real-time updates")
        doc.save(str(doc_v1))

        # Convert version 2
        print("Converting v2 to markdown...")
        md_v2, _ = converter.convert_to_markdown(doc_v1)

        with open(md_v2, encoding="utf-8") as f:
            content_v2 = f.read()

        print(f"V2 markdown: {len(content_v2)} characters")

        # Show diff simulation
        print("\nSimulated diff (what git would show):")
        print("-" * 70)

        # Simple diff
        v1_lines = content_v1.split("\n")
        v2_lines = content_v2.split("\n")

        if len(v2_lines) > len(v1_lines):
            print(f"@@ -{len(v1_lines)},0 +{len(v2_lines)},1 @@")
            new_lines = v2_lines[len(v1_lines) :]
            for line in new_lines:
                print(f"+ {line}")

        print("-" * 70)


def main() -> None:
    """Run all demos."""
    print("\n" + "=" * 70)
    print("VCS Document Converter - Demo Suite")
    print("=" * 70)
    print("\nThis demo showcases the key features of the VCS converter:")
    print("1. Basic conversion (binary to markdown)")
    print("2. Batch processing multiple documents")
    print("3. Bidirectional conversion (markdown back to binary)")
    print("4. Git workflow simulation")

    try:
        demo_basic_conversion()
        demo_batch_processing()
        demo_bidirectional_conversion()
        demo_workflow_simulation()

        print("\n" + "=" * 70)
        print("Demo Complete!")
        print("=" * 70)
        print("\nNext steps:")
        print("1. Try converting your own documents")
        print("2. Install the pre-commit hook: python install_hook.py")
        print("3. Read the README.md for detailed usage instructions")

    except Exception as e:
        print(f"\nError during demo: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
