"""Type stubs for pptx.enum.chart module."""

from enum import IntEnum

class XL_CHART_TYPE(IntEnum):
    """Specifies the type of chart."""

    # Column charts
    COLUMN_CLUSTERED = 51
    COLUMN_STACKED = 52
    COLUMN_STACKED_100 = 53
    THREE_D_COLUMN_CLUSTERED = 54
    THREE_D_COLUMN_STACKED = 55
    THREE_D_COLUMN_STACKED_100 = 56
    THREE_D_COLUMN = 57

    # Bar charts
    BAR_CLUSTERED = 57
    BAR_STACKED = 58
    BAR_STACKED_100 = 59
    THREE_D_BAR_CLUSTERED = 60
    THREE_D_BAR_STACKED = 61
    THREE_D_BAR_STACKED_100 = 62

    # Line charts
    LINE = 4
    LINE_MARKERS = 65
    LINE_MARKERS_STACKED = 66
    LINE_MARKERS_STACKED_100 = 67
    LINE_STACKED = 63
    LINE_STACKED_100 = 64
    THREE_D_LINE = 8

    # Pie charts
    PIE = 5
    PIE_EXPLODED = 69
    THREE_D_PIE = 70
    THREE_D_PIE_EXPLODED = 71
    PIE_OF_PIE = 68
    BAR_OF_PIE = 71

    # Area charts
    AREA = 1
    AREA_STACKED = 76
    AREA_STACKED_100 = 77
    THREE_D_AREA = 78
    THREE_D_AREA_STACKED = 79
    THREE_D_AREA_STACKED_100 = 80

    # Scatter (XY) charts
    XY_SCATTER = 75
    XY_SCATTER_LINES = 74
    XY_SCATTER_LINES_NO_MARKERS = 73
    XY_SCATTER_SMOOTH = 72
    XY_SCATTER_SMOOTH_NO_MARKERS = 75

    # Other chart types
    DOUGHNUT = 18
    DOUGHNUT_EXPLODED = 80
    RADAR = 82
    RADAR_FILLED = 82
    RADAR_MARKERS = 81
    SURFACE = 83
    SURFACE_TOP_VIEW = 85
    SURFACE_WIREFRAME = 84
    SURFACE_TOP_VIEW_WIREFRAME = 86
    BUBBLE = 15
    BUBBLE_THREE_D_EFFECT = 87
    STOCK_HLC = 88
    STOCK_OHLC = 89
    STOCK_VHLC = 90
    STOCK_VOHLC = 91
    CYLINDER_COL_CLUSTERED = 92
    CYLINDER_COL_STACKED = 93
    CYLINDER_COL_STACKED_100 = 94
    CYLINDER_BAR_CLUSTERED = 95
    CYLINDER_BAR_STACKED = 96
    CYLINDER_BAR_STACKED_100 = 97
    CYLINDER_COL = 98
    CONE_COL_CLUSTERED = 99
    CONE_COL_STACKED = 100
    CONE_COL_STACKED_100 = 101
    CONE_BAR_CLUSTERED = 102
    CONE_BAR_STACKED = 103
    CONE_BAR_STACKED_100 = 104
    CONE_COL = 105
    PYRAMID_COL_CLUSTERED = 106
    PYRAMID_COL_STACKED = 107
    PYRAMID_COL_STACKED_100 = 108
    PYRAMID_BAR_CLUSTERED = 109
    PYRAMID_BAR_STACKED = 110
    PYRAMID_BAR_STACKED_100 = 111
    PYRAMID_COL = 112
