#!/usr/bin/env python3
"""Generate the reStructuredText supported-format matrix for all2md.

The matrix is derived directly from the converter registry (which is populated
from ``all2md._converter_manifest``), so it can never drift from the set of
parsers and renderers that actually ship. The output is an ``.. include``-able
fragment (``.rst.inc``) consumed by ``docs/source/formats.rst``.

Regenerate manually with::

    python scripts/generate_formats_doc.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable, Optional

# Ensure project src directory is importable when run standalone
REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_PATH = REPO_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from all2md.converter_registry import registry  # noqa: E402

GENERATED_HEADER = (
    ".. NOTE: This file is auto-generated by scripts/generate_formats_doc.py\n"
    ".. Do not edit by hand; regenerate instead. It is rebuilt during the docs build.\n"
)

# Maximum extensions to list before collapsing the tail into "+N more".
_MAX_EXTENSIONS = 6

YES = "✓"  # check mark
NO = "—"  # em dash


def _format_extensions(extensions: list[str]) -> str:
    """Render an extension list as inline literals, collapsing long tails."""
    if not extensions:
        return NO
    shown = extensions[:_MAX_EXTENSIONS]
    rendered = ", ".join(f"``{ext}``" for ext in shown)
    remaining = len(extensions) - len(shown)
    if remaining > 0:
        rendered += f" (+{remaining} more)"
    return rendered


def _format_dependencies(metadata) -> str:
    """Render the optional dependencies for a converter, or 'built-in'."""
    packages: list[str] = []
    seen: set[str] = set()
    for pkg, _import_name, _version in metadata.required_packages:
        if pkg not in seen:
            seen.add(pkg)
            packages.append(pkg)
    for entry in metadata.optional_packages:
        pkg = entry[0]
        if pkg not in seen:
            seen.add(pkg)
            packages.append(pkg)
    if not packages:
        return "built-in"
    return ", ".join(packages)


def generate_matrix_lines() -> list[str]:
    """Build the RST list-table rows for every registered format."""
    lines: list[str] = [
        GENERATED_HEADER.rstrip(),
        "",
        ".. list-table:: Supported format matrix",
        "   :header-rows: 1",
        "   :widths: 18 8 8 46 20",
        "",
        "   * - Format",
        "     - Input",
        "     - Output",
        "     - Extensions",
        "     - Dependencies",
    ]

    for format_name in sorted(registry.list_formats()):
        metadata_list = registry.get_format_info(format_name)
        if not metadata_list:
            continue
        metadata = metadata_list[0]
        has_parser = metadata.parser_class is not None
        has_renderer = metadata.renderer_class is not None
        lines.extend(
            [
                f"   * - ``{format_name}``",
                f"     - {YES if has_parser else NO}",
                f"     - {YES if has_renderer else NO}",
                f"     - {_format_extensions(list(metadata.extensions))}",
                f"     - {_format_dependencies(metadata)}",
            ]
        )

    lines.append("")
    return lines


def generate_formats_document(output_path: Path) -> str:
    """Generate the format matrix fragment and write it to disk if changed."""
    document = "\n".join(generate_matrix_lines())
    if output_path.exists():
        current = output_path.read_text(encoding="utf-8")
        if current == document:
            return document
    output_path.write_text(document, encoding="utf-8")
    return document


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Generate the supported-format matrix fragment.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=REPO_ROOT / "docs" / "source" / "_generated_formats.rst.inc",
        help="Output fragment path (defaults to docs/source/_generated_formats.rst.inc)",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Iterable[str]] = None) -> None:
    """Generate the format matrix and print status."""
    args = parse_args(list(argv) if argv is not None else None)
    document = generate_formats_document(args.output)
    print(f"Generated format matrix with {len(document.splitlines())} lines -> {args.output}")


if __name__ == "__main__":
    main()
